init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '1.3'
    - nodejs_version: '0.12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install simple-bufferstream tape vinyl

build: off

test_script:
  - ps: 'node test.js #PowerShell'
  - cmd: node test.js

cache:
  - node_modules -> package.json
